
- name: Clear existing website files if user doesn't wish to customise base domain
  shell: rm -r /matrix/nginx-proxy/data/matrix-domain/*
  when: customise_base_domain_website|bool == false

- name: Enable index.html creation if user doesn't wish to customise base domain
  delegate_to: 127.0.0.1
  lineinfile:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    insertafter: # Base Domain Settings
    line: 'matrix_nginx_proxy_base_domain_homepage_enabled: true'
  when: customise_base_domain_website|bool == false

- name: Copy the new matrix_vars.yml file to the target machine
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    dest: /matrix/awx/
    mode: '0600'

- name: Reload vars in matrix_vars.yml
  include_vars:
    file: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'

- name: Update 'website' users password
  user:
    name: website
    password: "{{ sftp_password }}"
    update_password: always
  when: sftp_password != ""

- name: Save new 'Customise Base Domain Website' survey.json to the AWX tower, template
  delegate_to: 127.0.0.1
  template:
    src: 'roles/matrix-awx/templates/configure_base_domain_website.json.j2'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/configure_base_domain_website.json'

- name: Copy new 'Customise Base Domain Website' survey.json to target machine
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/configure_base_domain_website.json'
    dest:  '/matrix/awx/configure_base_domain_website.json'
    mode: 0644

- name: Recreate 'Customise Base Domain Website' job template
  delegate_to: 127.0.0.1
  tower_job_template:
    name: "{{ matrix_domain }} - 1 - Configure Base Domain Website"
    description: "Configure base domain website settings."
    extra_vars_path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    job_type: run
    job_tags: "start,setup-nginx-proxy"
    inventory: "{{ member_id }} Inventory"
    project: "{{ member_id }} - Matrix Docker Ansible Deploy"
    playbook: setup.yml
    credential: "{{ member_id }} - ChatOasis testing SSH"
    survey_enabled: true
    survey_spec: "{{ lookup('file', '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/configure_base_domain_website.json') }}"
    become_enabled: yes
    state: present
    verbosity: 1

