

- name: Enable index.html creation if user doesn't wish to customise base domain
  delegate_to: 127.0.0.1
  lineinfile:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    insertafter: '# Base Domain Settings'
  with_dict:
    'matrix_nginx_proxy_base_domain_homepage_enabled': 'true'
  when: customise_base_domain_website|bool == false

- name: Disable index.html creation to allow multi-file site if user does wish to customise base domain
  delegate_to: 127.0.0.1
  lineinfile:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    insertafter: '# Base Domain Settings'
  with_dict:
    'matrix_nginx_proxy_base_domain_homepage_enabled': 'false'
  when: customise_base_domain_website|bool == true

- name: Reload vars in matrix_vars.yml
  include_vars:
    file: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'

- name: Save new 'Customise Base Domain Website' survey.json to the AWX tower, template
  delegate_to: 127.0.0.1
  template:
    src: 'roles/matrix-awx/templates/configure_base_domain_website.json.j2'
    dest: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/configure_base_domain_website.json'

- name: Recreate 'Customise Base Domain Website' job template
  delegate_to: 127.0.0.1
  tower_job_template:
    name: "{{ matrix_domain }} - 1 - Configure Base Domain Website"
    description: "Configure base domain website settings."
    extra_vars_path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/extra_vars.yml'
    job_type: run
    job_tags: "start,setup-nginx-proxy"
    inventory: "{{ member_id }} Inventory"
    project: "{{ member_id }} - Matrix Docker Ansible Deploy"
    playbook: setup.yml
    credential: "{{ member_id }} - ChatOasis testing SSH"
    survey_enabled: true
    survey_spec: "{{ lookup('file', '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/configure_base_domain_website.json') }}"
    become_enabled: yes
    state: present
    verbosity: 1

# Copied over from provision stage

- name: Copy ssh_sftp.service file
  copy:
    src: './roles/matrix-awx/templates/sftp/ssh_sftp.service'
    dest: '/lib/systemd/system/ssh_sftp.service'
    mode: 0644

- name: Copy sshd config file
  copy:
    src: './roles/matrix-awx/templates/sftp/sshd_sftp_config'
    dest: '/etc/ssh/sshd_sftp_config'
    mode: 0644

- name: Ensure group "website" exists
  group:
    name: website
    state: present

- name: If user defines sftp_password, enable acccount / set password on 'website' account.
  user:
    name: website
    comment: SFTP user to set custom web files
    shell: /bin/false
    home: /home/website/
    group: website
    password: "{{ sftp_password | password_hash('sha512') }}"
    update_password: always
  when: sftp_password != ""

- name: If user account doesn't exist, create a disabled account for SFTP user 'website', with a primary group of 'website', and a shell of /bin/false
  user:
    name: website
    comment: SFTP user to set custom web files
    shell: /bin/false
    home: /home/website/
    group: website
    password: '!'
    update_password: on_create

- name: Setup SFTP users default root path
  shell: sudo usermod -d / website

- name: Create the ro /chroot directory if it doesn't exist. (/chroot/website has website:website permissions and is mounted to nginx container)
  file:
    path: /chroot
    state: directory
    owner: root
    group: root
    mode: '1755'

- name: Create the rw /chroot/website directory if it doesn't exist.
  file:
    path: /chroot/website
    state: directory
    owner: matrix
    group: matrix
    mode: '0777'

- name: Enable service ssh_sftp.service
  service:
    name: ssh_sftp.service
    enabled: yes

- name: Start service ssh_sftp.service
  service:
    name: ssh_sftp.service
    state: started

