

# Additional playbook to set the variable file
- import_tasks: "{{ role_path }}/tasks/set_variables_main.yml"
  when: run_setup|bool
  tags:
    - setup-all

# Additional playbook to set the variable file during element configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_element.yml"
  when: run_setup|bool
  tags:
    - setup-client-element

# Additional playbook to set the variable file during synapse configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_synapse.yml"
  when: run_setup|bool
  tags:
    - setup-synapse

# Additional playbook to set survey_spec file for configure element
- import_tasks: "{{ role_path }}/tasks/set_survey_configure_element.yml"
  when: run_setup|bool
  tags:
    - setup-client-element

# Additional playbook to set survey_spec file for configure synapse
- import_tasks: "{{ role_path }}/tasks/set_survey_configure_synapse.yml"
  when: run_setup|bool
  tags:
    - setup-synapse

