
# Additional playbook to set persistent facts
#- import_tasks: "{{ role_path }}/tasks/set_facts.yml"
#  when: run_setup|bool
#  tags:
#    - setup-all

# Additional playbook to set a variable file
- import_tasks: "{{ role_path }}/tasks/set_variables.yml"
  when: run_setup|bool
  tags:
    - setup-all

