
# Additional playbook to set persistent facts
#- import_tasks: "{{ role_path }}/tasks/set_facts.yml"
#  when: run_setup|bool
#  tags:
#    - setup-all

# Additional playbook to set a variable file
- import_tasks: "{{ role_path }}/tasks/set_variables.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-element
    - setup-synapse

# Additional playbook to set survey_spec file for configure element
- import_tasks: "{{ role_path }}/tasks/set_survey_configure_element.yml"
  when: run_setup|bool
  tags:
    - setup-element


# Additional playbook to set survey_spec file for configure synapse
- import_tasks: "{{ role_path }}/tasks/set_survey_configure_synapse.yml"
  when: run_setup|bool
  tags:
    - setup-synapse
