
# Load initial organisation variables from tower volume
- import_tasks: "{{ role_path }}/tasks/load_organisation_variables.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - always

# Create a user account if called
- import_tasks: "{{ role_path }}/tasks/create_user.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - create-user

# Import configs, media repo from /chroot/backup import
- import_tasks: "{{ role_path }}/tasks/import_awx.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - import-awx

# Configure SFTP so user can upload a static website
- import_tasks: "{{ role_path }}/tasks/customise_website_access_backup.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - setup-nginx-proxy

# Additional playbook to set the variable file during Element configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_element.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - setup-client-element

# Additional playbook to set the variable file during Synapse configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_synapse.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - setup-synapse

# Additional playbook to set the variable file during Jitsi configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_jitsi.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - setup-jitsi

# Additional playbook to set the variable file during Ma1sd configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_ma1sd.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - setup-ma1sd

# Additional playbook to set the variable file during Synapse Admin configuration
- import_tasks: "{{ role_path }}/tasks/set_variables_synapse_admin.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - setup-all

# Load newly formed matrix variables from tower volume
- import_tasks: "{{ role_path }}/tasks/load_matrix_variables.yml"
  when: run_setup|bool and matrix_awx_enabled|bool
  tags:
    - always

