
- name: Install prerequisite packages
  apt:
    name: 
      - sysstat
      - dnsutils
      - python3-dnspython
    state: present

- name: Calculate CPU usage statistics
  shell: iostat -c
  register: cpu_usage_stat
  no_log: True
    
- name: Print CPU usage statistics
  debug:
    msg: "{{ cpu_usage_stat.stdout.split('\n') }}"

- name: Calculate RAM usage statistics
  shell: free -mh
  register: ram_usage_stat
  no_log: True

- name: Print RAM usage statistics
  debug:
    msg: "{{ item }}"
  with_items: "{{ ram_usage_stat.stdout.split('\n') }}"

- name: Calculate free disk space
  shell: df -h
  register: disk_space_stat
  no_log: True

- name: Print free disk space
  debug:
    msg: "{{ item }}"
  with_items: "{{ disk_space_stat.stdout.split('\n') }}"

- name: Calculate size of Synapse database
  shell: du -sh /matrix/postgres/data
  register: db_size_stat
  no_log: True

- name: Print size of Synapse database
  debug:
    msg: "{{ item }}"
  with_items: "{{ db_size_stat.stdout.split('\n') }}"

- name: Calculate size of local media repository
  shell: du -sh /matrix/synapse/storage/media-store/local*
  register: local_media_size_stat
  ignore_errors: yes
  no_log: True

- name: Print size of local media repository
  debug:
    msg: "{{ item }}"
  with_items: local_media_size_stat.stdout_lines
  when: "{{ local_media_size_stat.stdout.split('\n') }}"

- name: Calculate size of remote media repository
  shell: du -sh /matrix/synapse/storage/media-store/remote*
  register: remote_media_size_stat
  ignore_errors: yes
  no_log: True

- name: Print size of remote media repository
  debug:
    msg: "{{ item }}"
  with_items: "{{ remote_media_size_stat.stdout.split('\n') }}"
  
# docker ps
# ram usage of all containers
# docker stats --all --no-stream --no-trunc

