
- name: Install prerequisite packages
  apt:
    name: sysstat
    state: present

- name: Calculate CPU usage statistics
  shell: iostat -c
  register: cpu_usage_stat
  no_log: True

- debug:
    msg: "{{ cpu_usage_stat.stdout }}"
    
- debug:
    msg: '{{ cpu_usage_stat.stdout }}'

- debug:
    msg: "{{ item }}"
  with_items: "{{ cpu_usage_stat.stdout_lines }}"

- debug:
    msg: "{{ cpu_usage_stat.stdout.split(\n) }}"
    
- name: Print CPU usage statistics
  debug:
    msg: "\n{{ cpu_usage_stat.stdout | regex_replace('\\n', '\n') | regex_replace('\\t', '\t') }}"
    
- name: Print CPU usage statistics
  debug:
    msg: '\n{{ cpu_usage_stat.stdout_lines }}'

- name: Print CPU usage statistics
  debug:
    msg: "{{ item | regex_replace('\\t', '\t') }}"
  with_items: '{{ cpu_usage_stat.stdout_lines }}'

- name: Calculate RAM usage statistics
  shell: free -mh
  register: ram_usage_stat
  no_log: True

- name: Print RAM usage statistics
  debug:
    msg: "{{ item }}"
  with_items: ram_usage_stat.stdout_lines

- name: Calculate free disk space
  shell: df -h
  register: disk_space_stat
  no_log: True

- name: Print free disk space
  debug:
    msg: "{{ item }}"
  with_items: disk_space_stat.stdout_lines

- name: Calculate size of Synapse database
  shell: du -sh /matrix/postgres/data
  register: db_size_stat
  no_log: True

- name: Print size of Synapse database
  debug:
    msg: "{{ item }}"
  with_items: db_size_stat.stdout_lines

- name: Calculate size of local media repository
  shell: du -sh /matrix/synapse/storage/media-store/local*
  register: local_media_size_stat
  ignore_errors: yes
  no_log: True

- name: Print size of local media repository
  debug:
    msg: "{{ item }}"
  with_items: local_media_size_stat.stdout_lines
  when: local_media_size_stat

- name: Calculate size of remote media repository
  shell: du -sh /matrix/synapse/storage/media-store/remote*
  register: remote_media_size_stat
  no_log: True

- name: Print size of remote media repository
  debug:
    msg: "{{ item }}"
  with_items: remote_media_size_stat.stdout_lines
  
# docker ps
# ram usage of all containers
# docker stats --all --no-stream --no-trunc

