# Setting variables so that they will be persisted in a file
# Depends on certain variables being defined the first run

- name: Ensure vars.yml file exists locally on AWX
  delegate_to: 127.0.0.1
  file:
    path: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/vars.yml'
    mode: '0600'
    state: touch
  register: local_awx_vars_file
  tags:
    - setup-all
    - setup-element
    - setup-synapse

- name: Ensure vars.yml file on remote target machine exists
  file:
    path: '/matrix/awx/vars.yml'
    mode: '0600'
    state: touch
  register: remote_vars_file
  tags:
    - setup-all
    - setup-element
    - setup-synapse

# ^ These might not be needed

#  - name: Record base variables on remote machine
#    lineinfile:
#      path: '{{ remote_vars_file.dest }}'
#      regexp: "^#? *{{ item.key | regex_escape() }}:"
#      line: "{{ item.key }}: {{ item.value }}"
#    with_dict:
#      'matrix_domain': '{{ matrix_domain }}'
#      'matrix_ssl_lets_encrypt_support_email': '{{ matrix_ssl_lets_encrypt_support_email }}'
#      'matrix_coturn_turn_static_auth_secret': '{{ matrix_coturn_turn_static_auth_secret }}'
#      'matrix_synapse_macaroon_secret_key': '{{ matrix_synapse_macaroon_secret_key }}'
#      'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
#      'matrix_jitsi_jicofo_component_secret': '{{ matrix_jitsi_jicofo_component_secret }}'
#      'matrix_jitsi_jicofo_auth_password': '{{ matrix_jitsi_jicofo_auth_password }}'
#      'matrix_jitsi_jvb_auth_password': '{{ matrix_jitsi_jvb_auth_password }}'
#      'matrix_jitsi_jibri_recorder_password': '{{ matrix_jitsi_jibri_recorder_password }}'
#      'matrix_jitsi_jibri_xmpp_password': '{{ matrix_jitsi_jibri_xmpp_password }}'
#      'matrix_nginx_proxy_base_domain_serving_enabled': #'{{ matrix_nginx_proxy_base_domain_serving_enabled }}'
#      'matrix_nginx_proxy_base_domain_homepage_enabled': #'{{ matrix_nginx_proxy_base_domain_homepage_enabled }}'
#      'matrix_vars_yml_snapshotting_enabled': '{{ matrix_vars_yml_snapshotting_enabled }}'
#    tags:
#      - setup-all

- name: Record base variables locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    path: '{{ local_awx_vars_file.dest }}'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
  with_dict:
    'matrix_domain': '{{ matrix_domain }}'
    'matrix_ssl_lets_encrypt_support_email': '{{ matrix_ssl_lets_encrypt_support_email }}'
    'matrix_coturn_turn_static_auth_secret': '{{ matrix_coturn_turn_static_auth_secret }}'
    'matrix_synapse_macaroon_secret_key': '{{ matrix_synapse_macaroon_secret_key }}'
    'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
    'matrix_jitsi_jicofo_component_secret': '{{ matrix_jitsi_jicofo_component_secret }}'
    'matrix_jitsi_jicofo_auth_password': '{{ matrix_jitsi_jicofo_auth_password }}'
    'matrix_jitsi_jvb_auth_password': '{{ matrix_jitsi_jvb_auth_password }}'
    'matrix_jitsi_jibri_recorder_password': '{{ matrix_jitsi_jibri_recorder_password }}'
    'matrix_jitsi_jibri_xmpp_password': '{{ matrix_jitsi_jibri_xmpp_password }}'
    'matrix_nginx_proxy_base_domain_serving_enabled': '{{ matrix_nginx_proxy_base_domain_serving_enabled }}'
    'matrix_nginx_proxy_base_domain_homepage_enabled': '{{ matrix_nginx_proxy_base_domain_homepage_enabled }}'
    'matrix_vars_yml_snapshotting_enabled': '{{ matrix_vars_yml_snapshotting_enabled }}'
  tags:
    - setup-all

#  - name: Record riot-web variables on remote machine
#    lineinfile:
#      path: '{{ remote_vars_file.dest }}'
#      regexp: "^#? *{{ item.key | regex_escape() }}:"
#      line: "{{ item.key }}: {{ item.value }}"
#    with_dict:
#      'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
#      'matrix_riot_web_jitsi_preferredDomain': '{{ matrix_riot_web_jitsi_preferredDomain }}'
#      'matrix_riot_web_brand': '{{ matrix_riot_web_brand }}'
#      'matrix_riot_web_default_theme': '{{ matrix_riot_web_default_theme }}'
#      'matrix_riot_web_branding_welcomeBackgroundUrl': '{{ matrix_riot_web_branding_welcomeBackgroundUrl }}'
#      'matrix_riot_web_registration_enabled': '{{ matrix_riot_web_registration_enabled }}'
#    tags:
#      - setup-riot-web

- name: Record Element-Web variables locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    path: '{{ local_awx_vars_file.dest }}'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
  with_dict:
    'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
    'matrix_riot_web_jitsi_preferredDomain': '{{ matrix_riot_web_jitsi_preferredDomain }}'
    'matrix_riot_web_brand': '{{ matrix_riot_web_brand }}'
    'matrix_riot_web_default_theme': '{{ matrix_riot_web_default_theme }}'
    'matrix_riot_web_branding_welcomeBackgroundUrl': '{{ matrix_riot_web_branding_welcomeBackgroundUrl }}'
    'matrix_riot_web_registration_enabled': '{{ matrix_riot_web_registration_enabled }}'
  tags:
    - setup-element

#  - name: Record synapse variables on remote machine
#    lineinfile:
#      path: '{{ remote_vars_file.dest }}'
#      regexp: "^#? *{{ item.key | regex_escape() }}:"
#      line: "{{ item.key }}: {{ item.value }}"
#    with_dict:
#      'matrix_synapse_allow_public_rooms_over_federation': '{{ matrix_synapse_allow_public_rooms_over_federation }}'
#      'matrix_synapse_enable_registration': '{{ matrix_synapse_enable_registration }}'
#      'matrix_synapse_federation_enabled': '{{ matrix_synapse_federation_enabled }}'
#    tags:
#      - setup-synapse

- name: Record synapse variables locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    path: '{{ local_awx_vars_file.dest }}'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
  with_dict:
    'matrix_synapse_allow_public_rooms_over_federation': '{{ matrix_synapse_allow_public_rooms_over_federation }}'
    'matrix_synapse_enable_registration': '{{ matrix_synapse_enable_registration }}'
    'matrix_synapse_federation_enabled': '{{ matrix_synapse_federation_enabled }}'
  tags:
    - setup-synapse

- name: Copy the new vars.yml file to the target machine
  delegate_to: "{{ server_ip4 }}"
  copy:
    src: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/vars.yml'
    dest: /matrix/awx/
    mode: '0600'
  tags:
    - setup-all
    - setup-synapse
    - setup-element


