
- name: Record synapse variables locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    insertafter: '# Synapse Settings'
  with_dict:
    'matrix_synapse_allow_public_rooms_over_federation': '{{ matrix_synapse_allow_public_rooms_over_federation }}'
    'matrix_synapse_enable_registration': '{{ matrix_synapse_enable_registration }}'
    'matrix_synapse_federation_enabled': '{{ matrix_synapse_federation_enabled }}'
    'matrix_synapse_enable_group_creation': '{{ matrix_synapse_enable_group_creation }}'
    'matrix_synapse_auto_join_rooms': '[{{ matrix_synapse_auto_join_rooms }}]'
    'matrix_synapse_use_presence': '{{ matrix_synapse_use_presence }}'
    'matrix_synapse_max_upload_size_mb': '{{ matrix_synapse_max_upload_size_mb }}'
    'matrix_synapse_enable_registration_captcha': '{{ matrix_synapse_enable_registration_captcha }}'
    'matrix_synapse_recaptcha_public_key': '{{ matrix_synapse_recaptcha_public_key }}'
    'matrix_synapse_recaptcha_private_key': '{{ matrix_synapse_recaptcha_private_key }}'

- name: Record synapse variables locally on AWX
  delegate_to: 127.0.0.1
  lineinfile:
    path: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    regexp: "^#? *{{ item.key | regex_escape() }}:"
    line: "{{ item.key }}: {{ item.value }}"
    insertafter: 'matrix_synapse_configuration_extension_yaml: |'
  with_dict:
    '  enable_registration_captcha': '{{ matrix_synapse_enable_registration_captcha }}'
    '  recaptcha_public_key': '{{ matrix_synapse_recaptcha_public_key }}'
    '  recaptcha_private_key': '{{ matrix_synapse_recaptcha_private_key }}'

# Considering:
#matrix_synapse_configuration_extension_yaml: |
#  recaptcha_private_key: private key
#  recaptcha_public_key: public key
#  enable_registration_captcha: false

- name: Copy the new vars.yml file to the target machine
  copy:
    src: '/var/lib/awx/projects/clients/{{ member_id }}/{{ subscription_id }}/matrix_vars.yml'
    dest: /matrix/awx/
    mode: '0600'
