
- name: Save new 'Configure Element' survey.json to the AWX tower using blockinfile
  delegate_to: 127.0.0.1
  blockinfile:
    dest: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/configure_element.json'
    block: |
      {
        "name": "",
        "description": "",
        "spec": [
          {
            "question_name": "Enable Element-Web",
            "question_description": "Set if Element-Web is enabled or not.",
            "required": true,
            "min": null,
            "max": null,
            "default": "{{ matrix_element_enabled }}",
            "choices": "true\nfalse",
            "new_question": true,
            "variable": "matrix_element_enabled",
            "type": "multiplechoice"
          },
          {
            "question_name": "Set Branding for Web Client",
            "question_description": "Sets the 'branding' seen in the tab and on the welcome page to a custom value.",
            "required": false,
            "min": 0,
            "max": 256,
            "default": "{{ matrix_element_brand }}",
            "choices": "",
            "new_question": true,
            "variable": "matrix_element_brand",
            "type": "text"
          },
          {
            "question_name": "Set Theme for Web Client",
            "question_description": "Sets the default theme for the web client, can be changed later by individual users.",
            "required": true,
            "min": null,
            "max": null,
            "default": "{{ matrix_element_default_theme }}",
            "choices": "light\ndark",
            "new_question": true,
            "variable": "matrix_element_default_theme",
            "type": "multiplechoice"
          },
          {
            "question_name": "Set Welcome Page Background",
            "question_description": "URL to Wallpaper, shown in background of the welcome page.",
            "required": false,
            "min": 0,
            "max": 1024,
            "default": "{{ matrix_element_branding_welcomeBackgroundUrl }}",
            "choices": "",
            "new_question": true,
            "variable": "matrix_element_branding_welcomeBackgroundUrl",
            "type": "text"
          },
          {
            "question_name": "Show Registration Button",
            "question_description": "If you show the registration button on the welcome page.",
            "required": true,
            "min": null,
            "max": null,
            "default": "{{ matrix_element_registration_enabled }}",
            "choices": "true\nfalse",
            "new_question": true,
            "variable": "matrix_element_registration_enabled",
            "type": "multiplechoice"
          }
        ]
      }
    backup: no
  tags:
    - setup-element

- name: Copy new 'Configure Element' survey.json to target machine
  copy:
    src: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/configure_element.json'
    dest:  '/matrix/awx/configure_element.json'
    mode: 0644
  tags:
    - setup-element

#- name: Recreate 'Configure Element' job template
#  delegate_to: 127.0.0.1
#  tower_job_template:
#    name: "{{ client_organisation }} - 1 - Configure Element"
#    description: "Configure Element client via survey."
#    extra_vars_path: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/extra_vars.yml'
#    job_type: run
#    job_tags: "start,setup-riot-web"
#    inventory: "{{ client_organisation }} Inventory"
#    project: "{{ client_organisation }} - Matrix Docker Ansible Deploy"
#    playbook: setup.yml
#    survey_enabled: true
#    survey_spec: "{{ lookup('file', '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/configure_element.json') }}"
#    become_enabled: yes
#    state: present
#    verbosity: 1
#  tags:
#    - setup-synapse

- name: Save new 'Configure Synapse' survey.json to the AWX tower using blockinfile
  delegate_to: 127.0.0.1
  blockinfile:
    dest: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/configure_synapse.json'
    block: |
      {
        "name": "",
        "description": "",
        "spec": [
          {
            "question_name": "Enable Public Registration",
            "question_description": "Controls whether people with access to the homeserver can register by themselves.",
            "required": true,
            "min": null,
            "max": null,
            "default": "{{ matrix_synapse_enable_registration }}",
            "choices": "true\nfalse",
            "new_question": true,
            "variable": "matrix_synapse_enable_registration",
            "type": "multiplechoice"
          },
          {
            "question_name": "Enable Federation",
            "question_description": "Controls whether Synapse will federate at all. Disable this to completely isolate your server from the rest of the Matrix network.",
            "required": true,
            "min": null,
            "max": null,
            "default": "{{ matrix_synapse_federation_enabled }}",
            "choices": "true\nfalse",
            "new_question": true,
            "variable": "matrix_synapse_federation_enabled",
            "type": "multiplechoice"
          },
          {
            "question_name": "Allow Public Rooms Over Federation",
            "question_description": "Controls whether remote servers can fetch this server's public rooms directory via federation. For private servers, you'll most likely want to forbid this.",
            "required": true,
            "min": null,
            "max": null,
            "default": "{{ matrix_synapse_allow_public_rooms_over_federation }}",
            "choices": "true\nfalse",
            "new_question": true,
            "variable": "matrix_synapse_allow_public_rooms_over_federation",
            "type": "multiplechoice"
          },
        ]
      }
    backup: no
  tags:
    - setup-synapse

- name: Copy new 'Configure Synapse' survey.json to target machine
  copy:
    src: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/configure_synapse.json'
    dest:  '/matrix/awx/configure_synapse.json'
    mode: 0644
  tags:
    - setup-synapse

#- name: Recreate 'Configure Synapse' job template
#  delegate_to: 127.0.0.1
#  tower_job_template:
#    name: "{{ client_organisation }} - 1 - Configure Synapse"
#    description: "Configure Synapse (homeserver) settings."
#    extra_vars_path: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/extra_vars.yml'
#    job_type: run
#    job_tags: "start,setup-synapse"
#    inventory: "{{ client_organisation }} Inventory"
#    project: "{{ client_organisation }} - Matrix Docker Ansible Deploy"
#    playbook: setup.yml
#    survey_enabled: true
#    survey_spec: "{{ lookup('file', '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/configure_synapse.json') }}"
#    become_enabled: yes
#    state: present
#    verbosity: 1
#  tags:
#    - setup-synapse

