# Ensure ansible up to date and pre-requisite variables are set
- import_tasks: "{{ role_path }}/tasks/sanity_check.yml"
  tags:
    - always

# Blank ??? strange...
- import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  when: "run_setup|bool"
  tags:
    - setup-all

# Cleans up a few left over file from previous outdated setups
- import_tasks: "{{ role_path }}/tasks/clean_up_old_files.yml"
  when: run_setup|bool
  tags:
    - setup-all

# Additional playbook to set persistent facts
#- import_tasks: "{{ role_path }}/tasks/set_facts.yml"
#  when: run_setup|bool
#  tags:
#    - setup-all

# Additional playbook to set a variable file
#- import_tasks: "{{ role_path }}/tasks/set_variables.yml"
#  when: run_setup|bool
#  tags:
#    - setup-all

# Installs docker and begins setup.
- import_tasks: "{{ role_path }}/tasks/server_base/setup.yml"
  when: run_setup|bool
  tags:
    - setup-all

# This needs to always run, because it populates `matrix_user_uid` and `matrix_user_gid`,
# which are required by many other roles.
- import_tasks: "{{ role_path }}/tasks/setup_matrix_user.yml"
  when: run_setup|bool
  tags:
    - always
    - setup-system-user

- import_tasks: "{{ role_path }}/tasks/setup_matrix_base.yml"
  when: run_setup|bool
  tags:
    - setup-all

- import_tasks: "{{ role_path }}/tasks/setup_well_known.yml"
  when: run_setup|bool
  tags:
    - setup-all
    - setup-ma1sd
    - setup-synapse
    - setup-nginx-proxy

- import_tasks: "{{ role_path }}/tasks/self_check_dns.yml"
  delegate_to: 127.0.0.1
  become: false
  when: run_self_check|bool
  tags:
    - self-check
