
# Setting variables so that they will be persisted in a file
# Depends on all these being defined the first run ??? i think so
#

#- hosts: all
#  remote_user: root
#  vars:
#    favcolor: blue
#  vars_files:
#    - /vars/external_vars.yml

  - name: record new variables 1
    command: '/bin/echo matrix_riot_web_enabled: {{ matrix_riot_web_enabled }} >> /matrix/vars_update.yml'

#   command: /bin/echo {{ item }}: {{ item }}
#    with:
#      - matrix_riot_web_enabled
#      - matrix_riot_web_brand
#      - matrix_riot_web_default_theme
#      - matrix_riot_web_branding_welcomeBackgroundUrl
#      - matrix_riot_web_registration_enabled
