# Setting variables so that they will be persisted in a file
# Depends on all these being defined the first run ??? i think so

#- hosts: all
#  remote_user: root
#  vars:
#    favcolor: blue
#  vars_files:
#    - /vars/external_vars.yml

#- hosts: all
#  tasks:
# uncomment previous two lines for local test
#
# shell: '/bin/echo matrix_riot_web_enabled: {{ matrix_riot_web_enabled }} >> /matrix/vars_update.yml'

  - name: Create a new vars.yml file locally on AWX
    delegate_to: 127.0.0.1
    file:
      path: '/var/lib/awx/projects/chatoasis-awx-variables/matrix.{{ matrix_domain }}/vars.yml'
      mode: '0600'
      state: touch
    register: local_awx_vars_file
    tags:
      - setup-all
      - setup-riot-web
      - setup-synapse

  - name: Create a new vars.yml file on remote target machine
    file:
      path: '/matrix/vars.yml'
      mode: '0600'
      state: touch
    register: remote_vars_file
    tags:
      - setup-all
      - setup-riot-web
      - setup-synapse

  - name: Record base variables on remote machine
    lineinfile:
      path: '{{ remote_vars_file.dest }}'
      regexp: "^#? *{{ item.key | regex_escape() }}:"
      line: "{{ item.key }}: {{ item.value }}"
    with_dict:
      'matrix_domain': '{{ matrix_domain }}'
      'matrix_ssl_lets_encrypt_support_email': '{{ matrix_ssl_lets_encrypt_support_email }}'
      'matrix_coturn_turn_static_auth_secret': '{{ matrix_coturn_turn_static_auth_secret }}'
      'matrix_synapse_macaroon_secret_key': '{{ matrix_synapse_macaroon_secret_key }}'
      'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
      'matrix_jitsi_jicofo_component_secret': '{{ matrix_jitsi_jicofo_component_secret }}'
      'matrix_jitsi_jicofo_auth_password': '{{ matrix_jitsi_jicofo_auth_password }}'
      'matrix_jitsi_jvb_auth_password': '{{ matrix_jitsi_jvb_auth_password }}'
      'matrix_jitsi_jibri_recorder_password': '{{ matrix_jitsi_jibri_recorder_password }}'
      'matrix_jitsi_jibri_xmpp_password': '{{ matrix_jitsi_jibri_xmpp_password }}'
      'matrix_nginx_proxy_base_domain_serving_enabled': '{{ matrix_nginx_proxy_base_domain_serving_enabled }}'
      'matrix_nginx_proxy_base_domain_homepage_enabled': '{{ matrix_nginx_proxy_base_domain_homepage_enabled }}'
      'matrix_vars_yml_snapshotting_enabled': '{{ matrix_vars_yml_snapshotting_enabled }}'
    tags:
      - setup-all

  - name: Record base variables locally on AWX
    delegate_to: 127.0.0.1
    lineinfile:
      path: '{{ local_awx_vars_file.dest }}'
      regexp: "^#? *{{ item.key | regex_escape() }}:"
      line: "{{ item.key }}: {{ item.value }}"
    with_dict:
      'matrix_domain': '{{ matrix_domain }}'
      'matrix_ssl_lets_encrypt_support_email': '{{ matrix_ssl_lets_encrypt_support_email }}'
      'matrix_coturn_turn_static_auth_secret': '{{ matrix_coturn_turn_static_auth_secret }}'
      'matrix_synapse_macaroon_secret_key': '{{ matrix_synapse_macaroon_secret_key }}'
      'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
      'matrix_jitsi_jicofo_component_secret': '{{ matrix_jitsi_jicofo_component_secret }}'
      'matrix_jitsi_jicofo_auth_password': '{{ matrix_jitsi_jicofo_auth_password }}'
      'matrix_jitsi_jvb_auth_password': '{{ matrix_jitsi_jvb_auth_password }}'
      'matrix_jitsi_jibri_recorder_password': '{{ matrix_jitsi_jibri_recorder_password }}'
      'matrix_jitsi_jibri_xmpp_password': '{{ matrix_jitsi_jibri_xmpp_password }}'
      'matrix_nginx_proxy_base_domain_serving_enabled': '{{ matrix_nginx_proxy_base_domain_serving_enabled }}'
      'matrix_nginx_proxy_base_domain_homepage_enabled': '{{ matrix_nginx_proxy_base_domain_homepage_enabled }}'
      'matrix_vars_yml_snapshotting_enabled': '{{ matrix_vars_yml_snapshotting_enabled }}'
    tags:
      - setup-all

  - name: Record riot-web variables on remote machine
    lineinfile:
      path: '{{ remote_vars_file.dest }}'
      regexp: "^#? *{{ item.key | regex_escape() }}:"
      line: "{{ item.key }}: {{ item.value }}"
    with_dict:
      'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
      'matrix_riot_web_jitsi_preferredDomain': '{{ matrix_riot_web_jitsi_preferredDomain }}'
      'matrix_riot_web_brand': '{{ matrix_riot_web_brand }}'
      'matrix_riot_web_default_theme': '{{ matrix_riot_web_default_theme }}'
      'matrix_riot_web_branding_welcomeBackgroundUrl': '{{ matrix_riot_web_branding_welcomeBackgroundUrl }}'
      'matrix_riot_web_registration_enabled': '{{ matrix_riot_web_registration_enabled }}'
    tags:
      - setup-riot-web

  - name: Record riot-web variables locally on AWX
    delegate_to: 127.0.0.1
    lineinfile:
      path: '{{ local_awx_vars_file.dest }}'
      regexp: "^#? *{{ item.key | regex_escape() }}:"
      line: "{{ item.key }}: {{ item.value }}"
    with_dict:
      'matrix_riot_web_enabled': '{{ matrix_riot_web_enabled }}'
      'matrix_riot_web_jitsi_preferredDomain': '{{ matrix_riot_web_jitsi_preferredDomain }}'
      'matrix_riot_web_brand': '{{ matrix_riot_web_brand }}'
      'matrix_riot_web_default_theme': '{{ matrix_riot_web_default_theme }}'
      'matrix_riot_web_branding_welcomeBackgroundUrl': '{{ matrix_riot_web_branding_welcomeBackgroundUrl }}'
      'matrix_riot_web_registration_enabled': '{{ matrix_riot_web_registration_enabled }}'
    tags:
      - setup-riot-web

  - name: Record synapse variables on remote machine
    lineinfile:
      path: '{{ remote_vars_file.dest }}'
      regexp: "^#? *{{ item.key | regex_escape() }}:"
      line: "{{ item.key }}: {{ item.value }}"
    with_dict:
      'matrix_synapse_allow_public_rooms_over_federation': '{{ matrix_synapse_allow_public_rooms_over_federation }}'
      'matrix_synapse_enable_registration': '{{ matrix_synapse_enable_registration }}'
      'matrix_synapse_federation_enabled': '{{ matrix_synapse_federation_enabled }}'
    tags:
      - setup-synapse

  - name: Record synapse variables locally on AWX
    delegate_to: 127.0.0.1
    lineinfile:
      path: '{{ local_awx_vars_file.dest }}'
      regexp: "^#? *{{ item.key | regex_escape() }}:"
      line: "{{ item.key }}: {{ item.value }}"
    with_dict:
      'matrix_synapse_allow_public_rooms_over_federation': '{{ matrix_synapse_allow_public_rooms_over_federation }}'
      'matrix_synapse_enable_registration': '{{ matrix_synapse_enable_registration }}'
      'matrix_synapse_federation_enabled': '{{ matrix_synapse_federation_enabled }}'
    tags:
      - setup-synapse

  - name: install deployment key
    copy:
      src: deploy-vault/pass.txt
      dest: "/tmp/pass.txt"
      mode: '0600'
    register: remote_pass_file
    when: remote_vars_file.dest is defined
    tags:
      - setup-all
      - setup-riot-web
      - setup-synapse

  - name: Make encrypted copy of vars on remote machine
    # infile == outfile
    script: deploy-vault/envaultify.sh '{{ remote_pass_file.dest }}' '{{ remote_vars_file.dest }}' '{{ remote_vars_file.dest }}.vault'
    when: remote_pass_file.dest is defined
    tags:
      - setup-all
      - setup-riot-web
      - setup-synapse
